### ISSUE TITLE
First run setup is missing devDependencies which causes compilation errors

### ISSUE THREAD

**Issue by Syynth** [ReactUnity/create#1]
When running `npx @reactunity/create` in a new project, when I then immediately run `npm start`, Webpack dev server throws compilation errors until I install the following dev dependencies:
- @typescript-eslint/eslint-plugin
- eslint-plugin-import
- eslint-plugin-react-hooks
- eslint-plugin-react

however, the following sequence will work correctly each time:
`npx @reactunity/create react`
`cd react`
`npm i -D @typescript-eslint/eslint-plugin eslint-plugin-import eslint-plugin-react-hooks eslint-plugin-react`
`npm start`

I have not tried with `yarn` as I do not have it installed/configured on my system, but I am running Windows 11, node 16.10.0 and npm 8.5.5

**Comment by KurtGokhan** [comment]
This is a long ongoing issue with eslint. https://github.com/eslint/eslint/issues/3458

As I tested, it didn't happen to me with npm versions 8.1 and 8.6. But I guess it can happen in some situations. Added these packages as dev dependencies now.
